language: objective-c
before_install:

    # install xctool
    - brew update
    - brew remove xctool
    - brew install xctool

    # update cocoapods
    - gem update cocoapods

    # print version summary
    - pod --version
    - xctool -version

# before_script:
#     # FIX: issue with pods and xcode 5 xcassets
#     - chmod -R +x ./scripts
#     - cp scripts/travis/Pods-resources.sh Pods/Pods-resources.sh
#     - cp scripts/travis/Pods-MKFoundationTests-resources.sh Pods/Pods-MKFoundationTests-resources.sh

script: xctool clean build test -arch i386 ONLY_ACTIVE_ARCH=NO
# script: xctool clean build test

notifications:
    email: false
